#!/bin/bash

config=$(cat /etc/thematic/$1.conf | grep -v "#") || exit 2

niri=$(echo "$config" | grep niri_layout | awk -F'"' '{print $2}') || exit 3
alacritty=$(echo "$config" | grep alacritty_colors | awk -F'"' '{print $2}') || exit 4
nvim=$(echo "$config" | grep nvim_colors | awk -F'"' '{print $2}') || exit 5
theme=$(echo "$config" | grep gtk_theme | awk -F'"' '{print $2}') || exit 6
icons=$(echo "$config" | grep gtk_icons | awk -F'"' '{print $2}') || exit 7
wallpaper=$(echo "$config" | grep wallpaper | awk -F'"' '{print $2}') || exit 8
rofi=$(echo "$config" | grep rofi | awk -F'"' '{print $2}') || exit 9
mako=$(echo "$config" | grep mako | awk -F'"' '{print $2}') || exit 10


# apply niri layout
mkdir -p ~/.config/niri
cp /etc/niri/config.kdl -u ~/.config/niri/config.kdl
cp /etc/niri/autostart.kdl -u ~/.config/niri/autostart.kdl
cp /etc/niri/window-rules.kdl -u ~/.config/niri/window-rules.kdl
cp /etc/niri/binds.kdl -u ~/.config/niri/binds.kdl
cp /etc/niri/$niri ~/.config/niri/theme.kdl

# apply alacritty color
mkdir -p ~/.config/alacritty
cp /etc/alacritty/$alacritty ~/.config/alacritty/alacritty.toml

# apply nvim color
mkdir -p ~/.config/nvim
cp /etc/xdg/nvim/$nvim ~/.config/nvim/init.lua

# apply nvim color
mkdir -p ~/.config/mako
cp /etc/mako/$mako ~/.config/mako/config

# apply rofi theme
mkdir -p ~/.config/rofi
echo "@theme \"/etc/thematic/$rofi\"" > ~/.config/rofi/color.rasi


# apply gtk theme and icons
gsettings set org.gnome.desktop.interface gtk-theme $theme
gsettings set org.gnome.desktop.interface icon-theme $icons

awww img /usr/share/wallpapers/$wallpaper --transition-type wipe --transition-angle 30 --transition-duration 0.2 --transition-fps 60

killall mako
mako --default-timeout 10000
