#!/usr/bin/env bash

for config in /etc/thematic/*; do

	# get the theme name
	theme=$(basename $config)

	# load the theme if it was selected, then exit
	if [ "$*" = "$theme" ]; then
		bash /usr/share/scripts/thematic $theme
		wait
		exit 0
	fi
done

if [ "$@" ]; then
	# Override the previously set prompt.
	echo -en "\x00prompt\x1fChange prompt\n"
else
	for config in /etc/thematic/*; do
		# get the theme name
		theme=$(basename $config)
		config=$(cat $config/theme.conf | grep -v "#")
		thumbnail=$(echo "$config" | grep THUMBNAIL | awk -F'"' '{print $2}') || exit 1
		echo -en "$theme\0icon\x1f/etc/thematic/$theme/$thumbnail\n"

	done
fi
