#!/bin/bash

config=$(cat /etc/thematic/$1/theme.conf | grep -v "#") || exit 2


copylist="$(echo "$config" | grep COPY | awk -F'"' '{print $2}')"
synclist="$(echo "$config" | grep SYNC | awk -F'"' '{print $2}')"
gtk="$(echo "$config" | grep GTK | awk -F'"' '{print $2}')"
icon="$(echo "$config" | grep ICON | awk -F'"' '{print $2}')"
wallpaper="$(echo "$config" | grep WALLPAPER | awk -F'"' '{print $2}')"

# SYNC files
IFS=$'\n'
for line in $synclist
do
	IFS=$' '
	pair=($(echo $line))
	rsync --mkpath "${pair[0]}" "$HOME/${pair[1]}"
done

# COPY files
IFS=$'\n'
for line in $copylist
do
	IFS=$' '
	pair=($(echo $line))
	rsync -c --mkpath "/etc/thematic/$1/${pair[0]}" "$HOME/${pair[1]}"
done

# GTK theme
gsettings set org.gnome.desktop.interface gtk-theme $gtk

# ICON theme
gsettings set org.gnome.desktop.interface icon-theme $icon

# apply WALLPAPER
awww img /etc/thematic/$1/$wallpaper --transition-type wipe --transition-angle 30 --transition-duration 0.2 --transition-fps 60

# reload mako
makoctl reload

